<a href="https://colab.research.google.com/github/OmidMustafa/XOR_python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# Vector 1-D array
a = [1,2,3] 

a = a + [1]

print(a)

# Numpy array 1-D 
b = np.array([4,5,6])

b = np.append(b,[7])



[1, 2, 3, 1]


In [4]:
A = np.array([[1,22,3],[4,5,6],[111,-11,33]])
B = np.array([[10,11,12],[13,14,15],[14,7,2.5]])

A.shape

(3, 3)

In [31]:

sum = np.sum(np.dot(A,B))
print(sum)
sum.dtype

5487.0


dtype('float64')

In [6]:
C = np.array([[10,11,12],[13,14,15],[16,17,18]])

C
C.shape

(3, 3)

In [10]:
K = np.array([[1,2,3],[1,2,3],[2,3,5]])

K.ndim

2

In [12]:
F = np.random.random(size=5)
F

array([0.55412327, 0.96144187, 0.1857229 , 0.24972063, 0.04994645])

In [16]:
L = np.random.rand(4,4,4)
L
L.shape

(4, 4, 4)

In [26]:
U = np.random.uniform(4.3,5.3,3)
print(U)
U.shape

[4.94584775 5.27103662 4.41071922]


(3,)

In [22]:
Z_3D = np.array([
                 [
                  [1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ],

                 [
                 [1,2,3],
                 [4,5,6],
                 [7,8,9]],

                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ],

                  [
                  [1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ]
                 ]
                )
print(Z_3D)
print("Number of Dimensions",Z_3D.ndim)
print("Size of Array",Z_3D.size)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
Number of Dimensions 3
Size of Array 36


In [36]:
B = np.array([[[
                [1,2,3],[1,2,3]],
                [[1,2,3],[1,2,3]],
                [[1,2,3],[1,2,3]]
               ]])
print(B)
print(B.ndim)
B.shape

[[[[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]]]]
4


(1, 3, 2, 3)

In [46]:
Z_3D = np.zeros_like([
                 [
                  [1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ],

                 [
                 [1,2,3],
                 [4,5,6],
                 [7,8,9]],

                  [[1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ],

                  [
                  [1,2,3],
                  [4,5,6],
                  [7,8,9]
                  ]
                 ]
                )
print(Z_3D)
print("Number of Dimensions ",Z_3D.ndim)
print("Size of Array",Z_3D.size)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
Number of Dimensions  3
Size of Array 36
